name: 反馈 Bug
description: 反馈遇到的问题
labels: [bug]
title: "[Bug] "
body:
  - type: markdown
    attributes:
      value: |
        为了使我们更好地帮助你，请提供以下信息。
  - type: textarea
    attributes:
      label: 问题描述
      description: 发生了什么情况？有什么现状？
    validations:
      required: true
  - type: textarea
    attributes:
      label: 复现步骤
      description: 如何复现
      placeholder: |
        1. 打开...
        2. 点击...
        3. 出现...状况
    validations:
      required: true
  - type: textarea
    attributes:
      label: 预期行为
      description: 正常情况下应该发生什么
    validations:
      required: true
  - type: textarea
    attributes:
      label: 实际行为
      description: 实际上发生了什么
    validations:
      required: true
  - type: textarea
    attributes:
      label: 截图或录屏
      description: 问题复现时候的截图或录屏
      placeholder: 点击文本框下面小长条可以上传文件
  - type: input
    attributes:
      label: 安卓版本
      render: shell
      placeholder: 12
    validations:
      required: true
  - type: input
    attributes:
      label: 哔哩漫游版本
      render: shell
      placeholder: 1.6.2
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 哔哩哔哩版本
      options:
        - 粉版（普通版）
        - 概念版
        - HD 版
        - play 版
      render: shell
      description: 目前仅支持粉版、概念版、HD 版和 play 版
  - type: input
    attributes:
      label: 哔哩哔哩版本号
      render: shell
      description: 非最新版本可能不受理
      render: 6.74.0
    validations:
      required: true
  - type: input
    attributes:
      label: 使用的框架和版本
      render: shell
      placeholder: LSPosed 1.8.2
    validations:
      required: true
  - type: textarea
    attributes:
      label: 其他
      description: 如哪部番、Magisk 版本等
  - type: textarea
    attributes:
      label: Logs/日志
      description: 请使用漫游自带的导出日志功能或者使用 `adb logcat`。无日志提交会被关闭。
      placeholder: 点击文本框下面小长条可以上传文件
    validations:
      required: true
