# This is a basic workflow that is manually triggered

name: 手动构建

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: '正式版'
        # Default value if no value is explicitly provided
        default: '正式版构建'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 正式版 ]

    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Build with Gradle
      run: ./gradlew assemble
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-artifact
        path: app/build/outputs
